server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/db_libreria_Alten?currentSchema=dbo
    username: postgres
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
  persistence:
    unit-name: PracticasAlten
