server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/db_libreria_Alten?currentSchema=dbo
    username: postgres
    password: root
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
      persistence:
      unit-name: PracticasAlten
      
      
  application:
    name: librerias-alten
  jmx:
    default-domain: ${spring.application.name}
    

springdoc:
  swagger-ui:
     enabled: true
     path: /swagger-ui.html  
  api-docs:
     path: /api-docs
  packagesToScan: com.alten.practica.controlador
  
cors:
  mapping: "/**"
  allowed-origins: http://localhost:4200, http://localhost:80
  allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
  allowed-headers: "*"
  
  
 ## CONFIGURACION DE LOS LOGS
##logging:
  ##level:
    ##root: info
  ##pattern:
    ##console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
  ##file: 
    ##name: log/${spring.application.name}.log
    ##max-size: 10MB
    ##total-size-cap: 100MB
    
## CORS ORIGIN

